name: geogame
description: "A new Flutter project."
publish_to: 'none'
version: 1.4.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.5
  easy_url_launcher: ^0.0.7
  font_awesome_flutter: ^10.10.0
  theme_mode_builder: ^2.0.0
  share_plus: ^12.0.0
  searchfield: ^1.3.5
  salomon_bottom_bar: ^3.3.2
  http: ^1.5.0
  package_info_plus: ^9.0.0
  permission_handler: ^12.0.1
  supabase_flutter: ^2.12.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter

flutter_icons:
  android: {
    "generate": true
  }
  web: {
    "generate": true
  }
  windows: {
    "generate": true
  }
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/bayraklar/
    - assets/sesler/