name: geogame
description: "A location guessing game based on maps, available on both mobile and PC."
publish_to: 'Github:KeremKuyucu'
version: 1.5.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  easy_url_launcher: ^0.0.7
  theme_mode_builder: ^2.0.0
  searchfield: ^1.3.5
  salomon_bottom_bar: ^3.3.2
  http: ^1.5.0
  package_info_plus: ^9.0.0
  supabase_flutter: ^2.12.0
  markdown: ^7.3.0
  flutter_html: ^3.0.0
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter

flutter_icons:
  android: {
    "generate": true
  }
  web: {
    "generate": true
  }
  windows: {
    "generate": true
  }
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/bayraklar/