name: geogame
description: "A location guessing game based on maps, available on both mobile, PC and web"
publish_to: 'Github:KeremKuyucu'
version: 1.5.7
environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  theme_mode_builder: ^2.0.0
  salomon_bottom_bar: ^3.3.2
  http: ^1.5.0
  package_info_plus: ^9.0.0
  supabase_flutter: ^2.12.0
  shared_preferences: ^2.5.4
  url_launcher: ^6.3.2
  uuid: ^4.5.2

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: {
    "generate": true
  }
  web: {
    "generate": true
  }
  windows: {
    "generate": true
  }
  image_path: "assets/images/logo.png"
# flutter pub run flutter_launcher_icons:main

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/geojson/
    - assets/lang/
    - assets/flags/